# Generated by Django 3.2.7 on 2022-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='英文名字')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('imgsrc', models.ImageField(blank=True, null=True, upload_to='static/images/authors', verbose_name='图片封面')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='书名')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='书名全')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文书名')),
                ('ISBN', models.CharField(blank=True, max_length=32, null=True, verbose_name='ISBN')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='定价')),
                ('product_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品编码')),
                ('publishDate', models.DateField(blank=True, null=True, verbose_name='出版时间')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='购买价格')),
                ('pages', models.IntegerField(blank=True, default=0, null=True, verbose_name='页数')),
                ('amount', models.IntegerField(blank=True, default=1, null=True, verbose_name='套装数量')),
                ('imgsrc', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='static/images/books', verbose_name='图片封面')),
                ('pack', models.CharField(blank=True, default='平装', max_length=32, null=True, verbose_name='包装')),
                ('size', models.CharField(blank=True, default='16开', max_length=32, null=True, verbose_name='开本')),
                ('words', models.CharField(blank=True, max_length=32, null=True, verbose_name='字数')),
                ('lables', models.CharField(blank=True, max_length=100, null=True, verbose_name='标签')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='内容简介')),
                ('review', models.TextField(blank=True, null=True, verbose_name='书评')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='名称')),
                ('addr', models.CharField(blank=True, max_length=64, null=True, verbose_name='地址')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
    ]
