# Generated by Django 3.2.7 on 2022-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='channel',
            field=models.CharField(blank=True, default='京东商城', max_length=32, null=True, verbose_name='购买渠道'),
        ),
    ]
