# Generated by Django 3.2.7 on 2022-02-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='URL',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='channel',
            field=models.CharField(blank=True, choices=[('京东商城', '京东商城'), ('当当网', '当当网')], default='当当网', max_length=32, null=True, verbose_name='购买渠道'),
        ),
    ]
