# Generated by Django 3.2.7 on 2022-02-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20220221_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name_pinyin',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='名称拼音'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name_pinyin',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='名称拼音'),
        ),
    ]
