# Generated by Django 3.2.7 on 2022-02-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220221_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='author2books', to='book.Book', verbose_name='作品'),
        ),
    ]
