# Generated by Django 3.2.7 on 2022-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_author_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book2authors', to='book.Author', verbose_name='作者/编者'),
        ),
    ]
