# Generated by Django 3.2.7 on 2022-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(related_name='book2translator', to='book.Author', verbose_name='译者'),
        ),
    ]
