# Generated by Django 3.2.7 on 2022-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='author2books', to='book.Book', verbose_name='作品'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='book2authors', to='book.Author', verbose_name='作者/编者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, related_name='book2translator', to='book.Author', verbose_name='译者'),
        ),
    ]
