# Generated by Django 3.2.7 on 2022-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20220221_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='书名'),
        ),
    ]
