# Generated by Django 3.2.7 on 2022-02-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20220221_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, related_name='book2translator', to='book.Author', verbose_name='译者'),
        ),
    ]
