# Generated by Django 3.2.7 on 2022-02-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_book_buy_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='display_name',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='显示名称'),
        ),
    ]
