# Generated by Django 3.2.7 on 2022-02-24 14:54

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_author_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='static/images/authors', verbose_name='图片封面'),
        ),
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='显示名称'),
        ),
    ]
