# Generated by Django 3.2.7 on 2022-02-24 14:58

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20220224_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='static/images/books', verbose_name='图片封面'),
        ),
    ]
