# Generated by Django 3.2.7 on 2022-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='显示名称'),
        ),
    ]
