# Generated by Django 3.2.7 on 2022-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_author_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name_pinyin',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='名称拼音'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name_pinyin',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='名称拼音'),
        ),
    ]
