# Generated by Django 3.2.7 on 2022-02-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20220225_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称'),
        ),
    ]
