# Generated by Django 3.2.7 on 2022-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_translator'),
        ('order', '0002_order_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='order2books', to='book.Book', verbose_name='书籍'),
        ),
    ]
