# Generated by Django 3.2.7 on 2022-02-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_book_translator'),
        ('order', '0003_alter_order_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='order2books', to='book.Book', verbose_name='书籍'),
        ),
    ]
